version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: sample_api
    expose:
      - "5001"

  nginx:
    image: nginx:1.25-alpine
    container_name: sample_nginx
    ports:
      - "82:9003"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
    expose:
      - "9003"

  nginx-secondary:
    image: nginx:1.25-alpine
    container_name: sample_nginx_secondary
    ports:
      - "81:81"
    volumes:
      - ./nginx2/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
